build.xml
I would like to have a zipped package which contains all the resources to run hivemall except for base platforms (Hadoop and Hive).
The output zipped package contains the two resources. Both resources are needed in the tutorials. 
- hivemall-with-dependencies.jar
-  define-all.hive
I expect the zipped package simplify the description of installation and tutorials. 
Any comment would be highly appreciate it.
=> Add assemble task to build.xml

scripts/ddl/define-all-as-permanent.hive, scripts/ddl/define-all-excluding-macro.hive, scripts/ddl/define-all-treasuredata.hive, scripts/ddl/define-all.hive, scripts/ddl/treasuredata.ddl, src/main/java/hivemall/tools/EachTopKUDTF.java, src/main/java/hivemall/utils/collections/BoundedPriorityQueue.java, src/main/java/hivemall/utils/hadoop/HiveUtils.java
`each_top_k(int k, ANY group, double value, arg1, arg2, ..., argN)` returns a top-k records for each `group`. It returns a relation consists of `(int rank, double value, arg1, arg2, .., argN)`.
This function is particularly useful for applying a similarity/distance function where the computation complexity is **O(n^m)**.
* This UDTF assumes that input records are sorted by `group`. Use `DISTRIBUTED BY group SORTED BY group` to ensure that.
* It takes variable lengths arguments in `argN`. 
* The second argument `value` is used for the comparison.
* If k is less than 0, reverse order is used and `tail-K` records are returned for each `group`.
* Note that this function returns [a pseudo ranking](http://www.michaelpollmeier.com/selecting-top-k-items-from-a-list-efficiently-in-java-groovy/) …
=> Added each_top_k UDTF

src/main/java/hivemall/dataset/LogisticRegressionDataGeneratorUDTF.java
`prob_one` represents the probability of generation of label one. This fixed the comparison between random variable and the given probability.
=> Fix the logic of generation probability for label one

pom.xml, src/test/resources/log4j.properties
When INFO log-level enabled, error message 'No appenders could be found for logger' appears.
This pr avoids this issue.
=> Add absent configurations in log4j.properties

pom.xml
This pr prevents tests from failing when `-Dtest=xxx` given and no tests executed.
=> Add option failIfNoTests in maven-surefire-plugin

mixserv/src/main/java/hivemall/mix/server/MixServerHandler.java, mixserv/src/main/java/hivemall/mix/store/PartialResult.java, mixserv/src/test/java/hivemall/mix/server/PartialResultTest.java
This pr fixes the bugs that occurs when short-typed values overflowed or underflowed.
i.e., the original code returns 32767 if globalClock=0 and localClock=Short.MIN_VALUE.
However, a correct value is 32768.
=> Fix bugs in PartialResult#diffClock and add tests

.gitignore, bin/mixserv_daemon.sh, bin/run_mixserv_cluster.sh, bin/status_mixserv_cluster.sh, bin/stop_mixserv.sh, bin/stop_mixserv_cluster.sh, conf/mixserv_env.sh, conf/mixserv_list
This pr adds scripts to easily launch and stop MIX servers in a group of machines;
we add a list of hosts in `conf/mixserv_list`, then invoke `./bin/run_mixserv_cluster.sh` to launch MIX servers in the hosts. `./bin/stop_mixserv_cluster.sh` shuts down the servers.
We also query the running statuses of the servers by using  `./bin/status_mixserv_cluster.sh`.
=> Add scritps to launch/stop MIX servers

core/pom.xml, core/src/main/java/hivemall/ftvec/trans/BinarizeLabelUDTF.java, core/src/test/java/hivemall/ftvec/trans/TestBinarizeLabelUDTF.java, resources/ddl/define-all.hive
Expanding numeric labels to actual count of samples can contribute to accuracy improvement in some cases. `binarize_label` explode a record that keeps the count of positive/negative labeled samples into corresponding actual count of samples. For example,
|positive|negative|features|
|:----|:----|:----|
|2|3|"[a:1, b:2]"|
is converted into 
|features|label|
|:----|:----|
|"[a:1, b:2]"|0|
|"[a:1, b:2]"|0|
|"[a:1, b:2]"|1|
|"[a:1, b:2]"|1|
|"[a:1, b:2]"|1|
`binarize_label(int/long positive, int/long negative, ANY arg1, ANY arg2, ..., ANY argN)` 
returns (ANY arg1, ANY arg2, ..., ANY argN, int label) where label is 0 or 1.
=> Binarize Label UDTF

core/src/main/java/hivemall/evaluation/LogarithmicLossUDAF.java, resources/ddl/define-all-as-permanent.hive, resources/ddl/define-all.hive
Added a function to calculate Logarithmic Loss for binary classification.
Definition: https://www.kaggle.com/wiki/LogarithmicLoss
This evaluation is used in some competitions on kaggle.
https://www.kaggle.com/c/criteo-display-ad-challenge
https://www.kaggle.com/c/sf-crime
=> Add Logarithmic Loss UDAF to evaluation functions

core/src/main/java/hivemall/HivemallConstants.java, core/src/main/java/hivemall/ftvec/amplify/RandomAmplifierUDTF.java
```sql
WITH dual as (select 1 as c1, 2 c2)
select rand_amplify(5, '-help', c1, c2) from dual;
```
```
usage: rand_amplify(const int xtimes [, const string options], *) -
amplify the input records x-times in map-side [-buf <arg>] [-help]
[-seed <arg>]
-buf,--num_buffers <arg>   The number of rows to keep in a buffer
[default: 1000]
-help                      Show function help
-seed <arg>                Random seed value [default: -1L (random)]
```
=> Lewuathe support seed in rand amplify seed

core/src/main/java/hivemall/HivemallConstants.java, core/src/main/java/hivemall/ftvec/amplify/RandomAmplifierUDTF.java
see: #313 
In order to specify `seed` parameter not amplified column, we need to implement it as `rand_amplify_seed` separately.
=> [#313] Support seed parameter in rand_amplify_seed

.travis.yml
=> Remove an unnecessary entry in .travis.yml

.travis.yml
This update is to turn on tests for `/spark` submodules.
=> Turn on tests for spark-v1.6 and spark-v2.0

core/src/main/java/hivemall/anomaly/SDAR1D.java, core/src/main/java/hivemall/utils/math/MatrixUtils.java, core/src/test/java/hivemall/utils/math/MatrixUtilsTest.java
- Implement `arburg()`, an alternative way to estimate the AR(k) model parameters.
- [MATLAB's reference implementation](https://searchcode.com/codesearch/view/9503568/)
- [Python version w/o vectorization](https://github.com/takuti/datadog-anomaly-detector/blob/e414f41c669577ed7704368ea130f9e6e7016b21/core/changefinder/utils.py#L70-L119)
- Return `-A` instead of `A` in `aryule()`, `aryule2()` and `arburg()`.
- Fix MarixUtilsTest in order to successfully pass unit testing for the module.
=> Implement `arburg()` and some minor fixes on MatrixUtils

core/src/main/java/hivemall/anomaly/ChangeFinder1D.java, core/src/main/java/hivemall/anomaly/ChangeFinder2D.java, core/src/main/java/hivemall/anomaly/SDAR1D.java, core/src/main/java/hivemall/anomaly/SDAR2D.java, core/src/main/java/hivemall/utils/math/MathUtils.java
By keeping the last `_mu` and `_sigma` in the SDAR algorithm as `_muOld` and `_sigmaOld`, we are now able to compute the Hellinger distance between the models before/after update. Usage is demonstrated as comments in **ChangeFinder1D** and **ChangeFinder2D**.
Computation of the Hellinger distance between two (multivariate) normal distributions are implemented on **MathUtils**.
Unit tests have not been implemented yet. However, I have confirmed whether it works as expected by comparing the results of [Python implementation](https://github.com/takuti/datadog-anomaly-detector/blob/e1c0523d8358a872fc3d59e28bb6c8411782934a/core/changefinder/changefinder_1d.py#L181-L202).
- mu1: 2.25635999045 
- sigma1: 1.56789907203 
- mu2: 2.37802392246
- sigma2: 4.5496514822
For the above parameters, the …
=> Support Hellinger-distance-based scoring both on SDAR 1D and 2D

core/src/main/java/hivemall/evaluation/AUCUDAF.java, core/src/main/java/hivemall/evaluation/BinaryResponsesMeasures.java, core/src/main/java/hivemall/evaluation/GradedResponsesMeasures.java, core/src/main/java/hivemall/evaluation/MAPUDAF.java, core/src/main/java/hivemall/evaluation/MRRUDAF.java, core/src/main/java/hivemall/evaluation/NDCGUDAF.java, core/src/main/java/hivemall/evaluation/PrecisionUDAF.java, core/src/main/java/hivemall/evaluation/RecallUDAF.java, core/src/main/java/hivemall/utils/hadoop/HiveUtils.java, core/src/test/java/hivemall/evaluation/BinaryResponsesMeasuresTest.java, core/src/test/java/hivemall/evaluation/GradedResponsesMeasuresTest.java
(extended from #321 )
- Update the original nDCG implementation w/ supporting graded responses
- Implement new ranking measures (for binary responses)
- Precision
- Recall
- MRR (Mean Reciprocal Rank)
- MAP (Mean Average Precision)
- AUC (the area under the ROC curve)
All of the above measures have the same interfaces as:
- `ndcg(array rankItems, array correctItems [, const int recommendSize = rankItems.size])`
- **Binary** (other measures are also same)
- `rankItems` &mdash; Ranked list of recommended item IDs
- `correctItems` &mdash; List of truth item IDs
- **Graded** (only NDCG)
- `rankItems` &mdash; Ordered list of structs <relScore, item> for recommended items
- `correctItems` &mdash; Ordered list of relScores for truth items
- `precision(rankItems, correctItems, recommendSize)`
- …
=> Implement additional ranking measures

pom.xml, spark/spark-1.6/pom.xml, spark/spark-2.0/pom.xml
This pr is to remove an unnecessary suffix number in jar from `hivemall-spark-2.0.0_2.11.8-0.4.2-rc.2-with-dependencies.jar` to `hivemall-spark-2.0_2.11-0.4.2-rc.2-with-dependencies.jar`.
=> Fix spark version number for jar

spark/spark-2.0/src/main/scala/org/apache/spark/sql/hive/HivemallOps.scala, spark/spark-2.0/src/test/scala/org/apache/spark/sql/hive/ModelMixingSuite.scala, spark/spark-2.0/src/test/scala/org/apache/spark/sql/hive/benchmark/MiscBenchmark.scala
This pr is to add benchmark code.
FYI: HiveUDF in spark eats 2x more processor time than the others because of valcano-style iterations, object inspectors, reflections, ...:
```
Java HotSpot(TM) 64-Bit Server VM 1.8.0_31-b13 on Mac OS X 10.10.2
Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
sigmoid functions:       Best/Avg Time(ms)    Rate(M/s)   Per Row(ns)   Relative
--------------------------------------------------------------------------------
exprs                         7708 / 8173          3.4         294.0       1.0X
closure                       7722 / 8342          3.4         294.6       1.0X
spark-udf                     7963 / 8350          3.3         303.8       1.0X
hive-udf                    13977 / 14050          1.9         533.2       0.6X
```
=> Add misc benchmark code for spark stuffs

spark/spark-1.6/src/main/scala/org/apache/spark/sql/hive/HivemallOps.scala, spark/spark-1.6/src/test/scala/org/apache/spark/sql/hive/HivemallOpsSuite.scala, spark/spark-2.0/src/main/scala/org/apache/spark/sql/hive/HivemallOps.scala, spark/spark-2.0/src/test/scala/org/apache/spark/sql/hive/HivemallOpsSuite.scala, spark/spark-2.0/src/test/scala/org/apache/spark/sql/hive/benchmark/MiscBenchmark.scala
FYI: The results are as follows;
```
Java HotSpot(TM) 64-Bit Server VM 1.8.0_31-b13 on Mac OS X 10.10.2
Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
top-k (k=8):            Best/Avg Time(ms)    Rate(M/s)   Per Row(ns)   Relative
-------------------------------------------------------------------------------
rank                       57267 / 59267          0.5        2184.5       1.0X
each_top_k                 40415 / 44812          0.6        1541.7       1.4X
```
=> Add benchmark code for each_top_k

spark/spark-2.0/src/main/scala/org/apache/spark/sql/catalyst/expressions/EachTopK.scala, spark/spark-2.0/src/main/scala/org/apache/spark/sql/hive/HivemallOps.scala, spark/spark-2.0/src/test/scala/org/apache/spark/sql/hive/HiveUdfSuite.scala, spark/spark-2.0/src/test/scala/org/apache/spark/sql/hive/HivemallOpsSuite.scala, spark/spark-2.0/src/test/scala/org/apache/spark/sql/hive/benchmark/MiscBenchmark.scala
This pr is to implement more efficient top-k processing on DataFrame/Spark.
The final benchmark results are as follows;
```
top-k (k=100):                           Best/Avg Time(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------
rank                                        62748 / 62862          0.4        2393.6       1.0X
each_top_k (hive-udf)                       41421 / 41736          0.6        1580.1       1.5X
each_top_k (exprs)                          15793 / 16394          1.7         602.5       4.0X
```
=> Implement EachTopK as a generator expression

pom.xml, spark/spark-1.6/pom.xml, spark/spark-2.0/pom.xml, spark/spark-common/pom.xml
This pr to brush up Spark-related `pom.xml`s
- Fix wrong scopes in dependencies
- Remove `build-helper-maven-plugin` because we hit errors in some conditions. This pr is to add new properties `scala.binary.version` and `spark.binary.version`. The properties are along with Spark ones.
- Brush up options in `scala-maven-plugin` and `scalatest-maven-plugin`. The fixed options are almost same with Spark ones.
=> Brush up spark/pom.xml

spark/spark-2.0/src/main/scala/org/apache/spark/sql/hive/HivemallGroupedDataset.scala, spark/spark-2.0/src/main/scala/org/apache/spark/sql/hive/HivemallOps.scala, spark/spark-2.0/src/test/scala/org/apache/spark/sql/hive/HivemallOpsSuite.scala, spark/spark-2.0/src/test/scala/org/apache/spark/sql/hive/ModelMixingSuite.scala, spark/spark-2.0/src/test/scala/org/apache/spark/sql/hive/XGBoostSuite.scala, spark/spark-2.0/src/test/scala/org/apache/spark/streaming/HivemallFeatureOpsSuite.scala
This pr is to remove weird `groupby` clauses in the spark module.
In the current version, `voted_avg()` is used like;
```
df.select(...).groupby.voted_avg()
```
This pr changes this in a Spark way.
```
df.select(...).groupBy.voted_avg()
```
=> Inject the Hivemall aggregate functionality in RelationalGroupedDataset
